backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads" # Adjust if you want to store media in a different location
public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    delete: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "string" }
