backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "public/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    delete: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "string" }
      - { name: "test", label: "Test", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }
